version: 0.2

env:
  variables:
    S3_BUCKET: anton-khitrov-codebuild
    STACK_NAME: Anton-Khitrov-Sam-CloudFormation
    REGION: us-west-2

phases:
  install:
    runtime-versions:
      java: corretto17
      python: 3.13
    commands:
      # Install SBT
      - echo "Installing SBT for YUM..."
      - curl -L https://www.scala-sbt.org/sbt-rpm.repo > sbt-rpm.repo
      - mv sbt-rpm.repo /etc/yum.repos.d/
      - yum install -y sbt
      - sbt sbtVersion

      # Install SAM CLI
      - curl -Lo sam.zip https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
      - unzip -q sam.zip -d sam-installation > /dev/null
      - ./sam-installation/install
      - export PATH=$PATH:/root/.local/bin
      - sam --version

  build:
    commands:
      - echo "🔨 Building Scala fat jar using sbt assembly..."
      - sbt clean assembly

      - echo "📦 Packaging Python Lambda dependencies..."
      - cd $CODEBUILD_SRC_DIR
      - ls -la src/main/
      - mkdir -p package
      - cp src/main/lambda/upload_notifications.py package/
      - cd package
      - zip -r9 ../lambda-deploy.zip .

  post_build:
    commands:
      - echo "📦 Packaging SAM application..."
      - cd $CODEBUILD_SRC_DIR
      - pwd
      - sam package --template-file sam_template.yaml --output-template-file packaged.yaml --s3-bucket $S3_BUCKET --region $REGION
      # - echo "🚀 Deploying SAM application..."
      # - sam deploy --template-file packaged.yaml --stack-name $STACK_NAME --capabilities CAPABILITY_IAM --region $REGION

artifacts:
  files:
    - target/scala-2.13/epam-study-app-0.1.0.jar
    - lambda-deploy.zip
    - packaged.yaml
  discard-paths: yes
