version: 0.2

env:
  variables:
    S3_BUCKET: anton-khitrov-codebuild
    STACK_NAME: Anton-Khitrov-Sam-CloudFormation
    REGION: us-west-2
    ECR_REPO_NAME: anton-khitrov/final-app
    IMAGE_TAG: latest

phases:
  install:
    runtime-versions:
      java: corretto17
      python: 3.13
    commands:
      # Install SBT
      - echo "Installing SBT for YUM..."
      - curl -L https://www.scala-sbt.org/sbt-rpm.repo > sbt-rpm.repo
      - mv sbt-rpm.repo /etc/yum.repos.d/
      - yum install -y sbt
      - sbt sbtVersion

      # Install SAM CLI
      - curl -Lo sam.zip https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
      - unzip -q sam.zip -d sam-installation > /dev/null
      - ./sam-installation/install
      - export PATH=$PATH:/root/.local/bin
      - sam --version
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REPO_URI=$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$ECR_REPO_NAME
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com
  build:
    commands:
      - echo "🔨 Building Scala fat jar using sbt assembly..."
      - sbt clean assembly

      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $ECR_REPO_NAME:$IMAGE_TAG .
      - docker tag $ECR_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$ECR_REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo "📦 Packaging SAM application..."
      - cd $CODEBUILD_SRC_DIR
      - pwd
      - sam package --template-file sam_template.yaml --output-template-file packaged.yaml --s3-bucket $S3_BUCKET --region $REGION

      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$ECR_REPO_NAME:$IMAGE_TAG

artifacts:
  files:
    #  - target/scala-2.13/epam-study-app-0.1.0.jar
    - packaged.yaml
  discard-paths: yes
